### ISSUE TITLE
CsvOutputWarning

### ISSUE THREAD

**Issue by marshalljacobs12** [marshalljacobs12/dowel#1]
@zequnyu @avnishn  CsvOutputWarning in csv_output.py is designed to warn about inconsistent keys between the TabularInput and the CsvOutput because CsvOutput currently handles these situations conservatively. Since that's no longer the desired functionality, can I get rid of CsvOutputWarning or will it be used in some other situation?

**Comment by avnishn** [comment]
You should modify the src and tests as necessary in order to achieve the desired output. E.g. the warning should be removed
